# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Act Now

consumes:
  - application/json

produces:
  - application/json

paths:
  /demonstration:
    get:
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:275223619344:function:act-now-api/invocations
        credentials: arn:aws:iam::275223619344:role/service-role/lambdaroleactnow
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "operation" : "getDemonstrations",
              "body" : $input.json('$')
            }
        responses:
          "default":
            statusCode: "200"

      description: |
        Gets `Demonstration` objects.
        Optional query param of **size** determines
        size of returned array
      parameters:
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
        -
          name: location
          in: query
          description: location id
          required: false
          type: integer
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Demonstration"

    post:
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:275223619344:function:act-now-api/invocations
        credentials: arn:aws:iam::275223619344:role/service-role/lambdaroleactnow
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "operation" : "createDemonstration",
              "body" : $input.json('$')
            }
        responses:
          "default":
            statusCode: "200"

      description: Creates `Demonstration` object
      parameters:
        - name: name
          in: body
          description: Demonstration properties
          required: true
          schema:
            $ref: "#/definitions/Demonstration"

      responses:
        "200":
          description: Succesful response
  /user:
    # This is a HTTP operation
    get:
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:275223619344:function:act-now-api/invocations
        credentials: arn:aws:iam::275223619344:role/service-role/lambdaroleactnow
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "operation" : "getUsers",
              "body" : $input.json('$')
            }
        responses:
          "default":
            statusCode: "200"

      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `User` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
    post:
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:275223619344:function:act-now-api/invocations
        credentials: arn:aws:iam::275223619344:role/service-role/lambdaroleactnow
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "operation" : "createUser",
              "body" : $input.json('$')
            }
        responses:
          "default":
            statusCode: "200"

      description: add user
      parameters:
        - name: name
          in: body
          description: user properties
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
  
  /user/{id}:
    get:
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:275223619344:function:act-now-api/invocations
        credentials: arn:aws:iam::275223619344:role/service-role/lambdaroleactnow
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "operation" : "getUserById",
              "body" : $input.json('$'),
              "id" : "$input.params('id')"
            }
        responses:
          "default":
            statusCode: "200"

      description: get user
      parameters:
        - name: id
          in: path
          type: integer
          description: user id
          required: true
      responses:
        "200":
          description: success
          schema:
            $ref: "#/definitions/User"


  /demonstration/{id}:
    get:
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:275223619344:function:act-now-api/invocations
        credentials: arn:aws:iam::275223619344:role/service-role/lambdaroleactnow
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "operation" : "getDemonstrationById",
              "body" : $input.json('$'),
              "id" : "$input.params('id')"
            }
        responses:
          "default":
            statusCode: "200"

      description: get a demonstration
      parameters:
        -
          name: id
          type: integer
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetDemonstrationResponse"
  /demonstration/{id}/follow:
    post:
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:275223619344:function:act-now-api/invocations
        credentials: arn:aws:iam::275223619344:role/service-role/lambdaroleactnow
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "operation" : "followDemonstration",
              "body" : $input.json('$'),
              "id" : "$input.params('id')"
            }
        responses:
          "default":
            statusCode: "200"

      description: follow a demonstration
      parameters:
        - name: id
          type: integer
          in: path
          required: true
        - name: user
          in: body
          description: follow properties
          required: true
          schema:
            $ref: "#/definitions/Follow"
      responses:
        "200":
          description: success
          schema:
            $ref: "#/definitions/FollowResponse"

  /location:
    get:
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:275223619344:function:act-now-api/invocations
        credentials: arn:aws:iam::275223619344:role/service-role/lambdaroleactnow
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "operation" : "getLocations",
              "body" : $input.json('$')
            }
        responses:
          "default":
            statusCode: "200"

      description: get location list
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetLocationsResponse"


definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        description: user id
      firstname:
        type: string
        description: user's first name
      lastname:
        type: string
        description: user's last name
      phone:
        type: string
        description: user's phone number
      location:
        type: integer
        description: location id
      following:
        type: array
        description: demonstrations user is following
        items:
          type: integer
          description: demonstration id
        
    required:
      - firstname
      - lastname
      - phone
      - location

  Demonstration:
    type: object
    properties:
      id:
        type: integer
        description: demonstration id
      name:
        type: string
        description: demonstration name
      location:
        type: integer
        description: location id
      date:
        type: integer
        description: datetime
      description:
        type: string
        description: description of demonstration
      organizers:
        type: array
        description: array of organizer user ids
        items:
          type: integer
          description: organizer's user ID
    required:
      - name
      - location
      - date
      - description
      - organizers
      
  Location:
    type: object
    properties:
      id:
        type: integer
        description: location id
      name:
        type: string
        description: location name
    required:
        - name
    
  Follow:
    type: object
    properties:
      id:
        type: integer
        description: demonstration id
      user:
        type: integer
        description: user id
    required:
        - user
    
  GetDemonstrationResponse:
    description: list of demonstrations
    type: array
    items:
      $ref: "#/definitions/Demonstration"

  GetLocationsResponse:
    description: list of locations
    type: array
    items:
      $ref: "#/definitions/Location"
  
  FollowResponse:
    description: follow response
    type: object
    properties:
      id:
        type: integer
        description: demonstration id
      user:
        type: integer
        description: user id
  

  ErrorResponse:
    description: error
